import React, { useState, useEffect, createContext, useContext, useRef, useMemo } from 'react';
import axios from 'axios';
import { io } from 'socket.io-client';
import Peer from 'peerjs';
import {
    Activity, Clock, Video, PhoneCall, ChevronRight, Send, ArrowRightCircle, LogOut, ChevronLeft, Heart,
    Zap, Share2, ClipboardList, X, FileText, UserCheck, HeartPulse, History, AlertTriangle, UploadCloud, User, Ruler, Scale, ShieldAlert, Star, MapPin,
    Monitor, Info, Bell, CheckCircle2, AlertCircle, TrendingUp
} from 'lucide-react';

const API_BASE = 'https://sahay-6doo.onrender.com/api';
const socket = io('https://sahay-6doo.onrender.com');

const AuthContext = createContext(null);
const AuthProvider = ({ children }) => {
    const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('user')));
    const [token, setToken] = useState(() => localStorage.getItem('token'));
    const login = async (phone, name, role) => {
        try {
            const res = await axios.post(`${API_BASE}/auth/login`, { phone, name, role });
            localStorage.setItem('token', res.data.token);
            localStorage.setItem('user', JSON.stringify(res.data.user));
            setToken(res.data.token); setUser(res.data.user);
        } catch (e) { alert("Login failed."); }
    };
    const logout = () => { localStorage.removeItem('token'); localStorage.removeItem('user'); setUser(null); setToken(null); };
    return <AuthContext.Provider value={{ user, token, login, logout }}>{children}</AuthContext.Provider>;
};

// --- Clinical Report & Shared Access Dashboard ---

const PrivateReportView = ({ q, onBack, onShare }) => {
    const reasonObj = useMemo(() => {
        try { return JSON.parse(q?.reasoning || "{}"); }
        catch (e) { return { summary: q?.reasoning }; }
    }, [q]);

    return (
        <div className="container animate-up" style={{ maxWidth: '900px' }}>
            <div className="card" style={{ padding: '3rem', position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'absolute', top: '1.5rem', right: '1.5rem', background: '#f1f5f9', padding: '0.5rem 1rem', borderRadius: '8px', fontSize: '0.8rem', fontWeight: '800', color: '#64748b', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <ShieldAlert size={14} /> EXCLUSIVE PATIENT VIEW
                </div>
                <div className="report-header">
                    <div>
                        <h1 style={{ fontSize: '2rem' }}>AI Clinical Health Report</h1>
                        <p style={{ color: 'var(--text-muted)' }}>Generated by SAHAY Intelligence Engine</p>
                    </div>
                </div>

                <div style={{ background: q.severity === 'EMERGENCY' ? '#fff1f2' : '#f0f9ff', border: `1px solid ${q.severity === 'EMERGENCY' ? '#fecaca' : '#bae6fd'}`, padding: '2rem', borderRadius: '16px', marginBottom: '2rem' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                        <h3 style={{ color: q.severity === 'EMERGENCY' ? '#e11d48' : '#0369a1' }}>Pre-Consultation Assessment</h3>
                        <span className={`badge ${q.severity === 'EMERGENCY' ? 'emergency-bg' : 'moderate-bg'}`} style={{ padding: '0.6rem 1.5rem', fontSize: '1rem' }}>{q.severity}</span>
                    </div>
                    <p style={{ fontSize: '1.1rem', lineHeight: '1.6', color: '#1e293b' }}>{reasonObj.summary || q.reasoning}</p>
                </div>

                <div className="report-grid">
                    <div className="card" style={{ boxShadow: 'none', background: '#f8fafc' }}>
                        <h4 style={{ marginBottom: '1rem' }}>Personal Profile</h4>
                        <p><strong>Name:</strong> {q.profile?.name || 'User'}</p>
                        <p><strong>Age/Gender:</strong> {q.profile?.age}y, {q.profile?.gender}</p>
                        <p><strong>BMI Index:</strong> {q.profile?.bmi?.toFixed(1)}</p>
                    </div>
                    <div className="card" style={{ boxShadow: 'none', background: '#f8fafc' }}>
                        <h4 style={{ marginBottom: '1rem' }}>Medical Risks</h4>
                        <div style={{ color: '#e11d48', fontWeight: '700' }}><AlertCircle size={14} /> High Cardiac Sensitivity</div>
                        <div style={{ color: '#0369a1', fontWeight: '700' }}><CheckCircle2 size={14} /> Normal Respiratory Rhythm</div>
                    </div>
                </div>

                <div style={{ marginTop: '3rem', display: 'flex', gap: '1.5rem' }}>
                    <button className="outline" style={{ flex: 1 }} onClick={onBack}><ChevronLeft /> BACK TO CONSOLE</button>
                    <button className="primary" style={{ flex: 2, padding: '1.2rem' }} onClick={onShare}>SELECT DOCTOR & SHARE REPORT <ChevronRight /></button>
                </div>
            </div>
        </div>
    );
};

// --- Advanced Doctor Discovery Dashboard ---

const DoctorDiscovery = ({ user, q, onBack, onShare }) => {
    const [docs, setDocs] = useState([]);
    const fetchDocs = () => axios.get(`${API_BASE}/doctors`).then(res => setDocs(res.data));
    useEffect(() => { fetchDocs(); socket.on('queue_updated', fetchDocs); return () => socket.off('queue_updated', fetchDocs); }, []);

    return (
        <div className="container animate-up">
            <header style={{ marginBottom: '3rem' }}>
                <h1 style={{ fontSize: '2.5rem' }}>Select Clinical Specialist</h1>
                <p style={{ color: 'var(--text-muted)' }}>Compare real-time urgency-based queues for the most efficient consultation.</p>
            </header>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(380px, 1fr))', gap: '2rem' }}>
                {docs.map(d => (
                    <div key={d.id} className="card" style={{ borderTop: `10px solid ${d.queueLoad > 3 ? '#ef4444' : 'var(--primary)'}`, position: 'relative' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: '#f59e0b', fontWeight: '900' }}><Star size={20} fill="#f59e0b" /><span>{d.rating}</span></div>
                            <span className="badge routine-bg" style={{ fontSize: '0.7rem' }}>{d.specialty}</span>
                        </div>
                        <h3>{d.doctorName}</h3>
                        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1.5rem' }}><MapPin size={12} /> {d.address}</p>

                        <div style={{ background: '#f8fafc', padding: '1.5rem', borderRadius: '16px', marginBottom: '2rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #eef2ff', paddingBottom: '0.75rem', marginBottom: '0.75rem' }}>
                                <span style={{ fontSize: '0.85rem', fontWeight: '700', color: '#475569' }}>Real-time Priority Queue</span>
                                <span style={{ fontSize: '0.8rem', color: 'var(--primary)', fontWeight: '800' }}>Active: {d.queueLoad} Patients</span>
                            </div>
                            <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                                <div style={{ background: '#fef2f2', padding: '0.4rem 0.8rem', borderRadius: '8px', color: '#ef4444', fontSize: '0.75rem', fontWeight: '800' }}>{d.emergencyCount} EMERGENCY</div>
                                <div style={{ background: '#f0f9ff', padding: '0.4rem 0.8rem', borderRadius: '8px', color: '#0369a1', fontSize: '0.75rem', fontWeight: '800' }}>{d.queueLoad - d.emergencyCount} ROUTINE</div>
                            </div>
                        </div>

                        <button
                            className="primary"
                            style={{ width: '100%', padding: '1.25rem', background: q?.doctorId === d.id ? '#10b981' : 'var(--primary)' }}
                            onClick={() => onShare(d.id)}
                            disabled={q?.isShared && q?.doctorId !== d.id}
                        >
                            {q?.doctorId === d.id ? 'REPORT SHARED & QUEUED' : 'SHARE REPORT & JOIN QUEUE'} <Share2 size={18} style={{ marginLeft: '0.5rem' }} />
                        </button>
                    </div>
                ))}
            </div>
        </div>
    );
};

// --- Principal Patient Dashboard ---

const PatientDashboard = ({ user, setView, onStartCall }) => {
    const { data: q } = useQueueSync(user.id);
    const [page, setPage] = useState('MAIN');

    if (q?.profileMissing) return <SetupProfile userId={user.id} onComplete={() => window.location.reload()} />;

    const handleShare = async (docId) => {
        try {
            await axios.post(`${API_BASE}/book/share-report`, { userId: user.id, doctorId: docId });
            alert("Digital Report Shared Successfully. You are now in the doctor's priority queue.");
            setPage('MAIN');
        } catch (e) { alert(e.response?.data?.error || "Sharing failed."); }
    };

    if (page === 'REPORT') return <PrivateReportView q={q} onBack={() => setPage('MAIN')} onShare={() => setPage('DISCOVERY')} />;
    if (page === 'DISCOVERY') return <DoctorDiscovery user={user} q={q} onBack={() => setPage('MAIN')} onShare={handleShare} />;

    return (
        <div className="container animate-up">
            <header style={{ marginBottom: '3rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <h1 style={{ fontSize: '2.5rem' }}>Hello, <span className="text-gradient">{user.name}</span></h1>
                    <p style={{ color: 'var(--text-muted)' }}>Digital Clinical Hub & Priority Triage</p>
                </div>
            </header>

            <div className="dashboard-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(12, 1fr)', gap: '2rem' }}>
                <div className="card" style={{ gridColumn: 'span 4', textAlign: 'center' }}>
                    <div style={{ width: '80px', height: '80px', background: 'var(--primary-light)', borderRadius: '50%', margin: '0 auto 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><User size={40} color="var(--primary)" /></div>
                    <h3>Personal Profile</h3>
                    <p>{q?.profile?.age} years | {q?.profile?.gender} | {q?.profile?.bloodGroup}</p>
                    <div style={{ marginTop: '2rem', background: '#f8fafc', padding: '1.5rem', borderRadius: '16px' }}>
                        <p style={{ fontSize: '0.75rem', opacity: 0.6 }}>BODY MASS INDEX</p>
                        <h2 style={{ fontSize: '2rem', color: 'var(--primary)' }}>{q?.profile?.bmi?.toFixed(1)}</h2>
                    </div>
                </div>

                <div className="card" style={{ gridColumn: 'span 8', borderStyle: 'dashed', background: '#f8fafc', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                    {q?.inQueue ? (
                        <div style={{ textAlign: 'center' }}>
                            <FileText size={50} color={q.isShared ? '#10b981' : 'var(--primary)'} />
                            <h2 style={{ marginTop: '1rem' }}>{q.isShared ? 'Digital Report Shared' : 'Private AI Clinical Report Ready'}</h2>
                            <p style={{ color: 'var(--text-muted)', marginBottom: '2.5rem' }}>{q.isShared ? `Shared with Clinic ID: ${q.doctorId.slice(0, 8)}` : 'Review your structured clinical assessment before sharing with a specialist.'}</p>
                            <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }}>
                                <button className="primary" style={{ background: q.isShared ? '#10b981' : 'var(--primary)' }} onClick={() => setPage('REPORT')}>VIEW REPORT</button>
                                {!q.isShared && <button className="outline" onClick={() => setPage('DISCOVERY')}>FIND SPECIALIST & SHARE</button>}
                            </div>
                        </div>
                    ) : (
                        <div style={{ textAlign: 'center', opacity: 0.5 }}>
                            <ShieldAlert size={60} />
                            <h2 style={{ marginTop: '1rem' }}>No Assessment Found</h2>
                            <p>Start an AI Intake to generate your medical report.</p>
                        </div>
                    )}
                </div>

                <div className="card" style={{ gridColumn: 'span 12', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '2rem', background: 'var(--primary-light)', border: 'none' }}>
                    <div style={{ textAlign: 'center' }}><ClipboardList size={30} color="var(--primary)" /> <p style={{ fontWeight: '800', marginTop: '0.5rem' }}>Electronic Records</p></div>
                    <div style={{ textAlign: 'center' }}><HeartPulse size={30} color="var(--primary)" /> <p style={{ fontWeight: '800', marginTop: '0.5rem' }}>Heart Metrics</p></div>
                    <div style={{ textAlign: 'center' }}><TrendingUp size={30} color="var(--primary)" /> <p style={{ fontWeight: '800', marginTop: '0.5rem' }}>Vitals Analytics</p></div>
                    <div style={{ textAlign: 'center' }}><CheckCircle2 size={30} color="var(--primary)" /> <p style={{ fontWeight: '800', marginTop: '0.5rem' }}>ID Verification</p></div>
                </div>

                {q?.isShared && (
                    <div className="card animate-up" style={{ gridColumn: 'span 12', border: '2px solid #10b981', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem 3rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '2rem' }}>
                            <div style={{ fontSize: '4rem', fontWeight: '900', color: '#10b981' }}>#{q.position}</div>
                            <div><h2 style={{ color: '#065f46' }}>Your Urgency Position</h2><p style={{ color: '#065f46', opacity: 0.8 }}>Organized by Medical Priority. Estimated wait: {q.position * 12} mins.</p></div>
                        </div>
                        {q.status === 'IN_CONSULTATION' && <button className="primary pulse" style={{ background: '#10b981' }} onClick={() => onStartCall(q.callRoomId, q.doctorPeerId)}>JOIN DIGITAL CONSULTATION</button>}
                    </div>
                )}
            </div>

            {!q?.inQueue && (
                <button className="primary pulse" style={{ position: 'fixed', bottom: '3rem', left: '50%', transform: 'translateX(-50%)', padding: '1.5rem 4rem', borderRadius: '50px', zIndex: 1000 }} onClick={() => setView('INTAKE')}>
                    START AI-POWERED CLINICAL ASSESSMENT
                </button>
            )}
        </div>
    );
};

// --- Standard Doctor Interface ---

const DoctorDashboard = ({ user, onStartCall }) => {
    const [q, setQ] = useState([]);
    const fetchQ = () => axios.get(`${API_BASE}/doctor/queue?doctorUserId=${user.id}`).then(res => setQ(res.data));
    useEffect(() => { fetchQ(); socket.on('queue_updated', fetchQ); return () => socket.off('queue_updated', fetchQ); }, []);

    return (
        <div className="container animate-up">
            <h1 className="text-gradient">Doctor Console</h1>
            <p style={{ color: 'var(--text-muted)' }}>Priority Triage Queue Management</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', marginTop: '3rem' }}>
                {q.map(x => (
                    <div key={x.id} className="card" style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '3rem', alignItems: 'center', borderLeft: `8px solid ${x.severity === 'EMERGENCY' ? '#ef4444' : '#f59e0b'}` }}>
                        <div>
                            <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '0.75rem' }}>
                                <span className={`badge ${x.severity === 'EMERGENCY' ? 'emergency-bg' : 'moderate-bg'}`}>{x.severity}</span>
                                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: '800' }}>Patient ID: {x.patientId.slice(0, 8)}</span>
                            </div>
                            <h2 style={{ fontSize: '1.5rem' }}>{x.name} ({x.age}y, {x.gender})</h2>
                        </div>
                        <div style={{ display: 'flex', gap: '1rem' }}>
                            <button className="outline"><FileText size={18} /> PRE-READ REPORT</button>
                            <button className="primary" onClick={() => {
                                const p = new Peer(); p.on('open', (pid) => {
                                    axios.post(`${API_BASE}/doctor/action`, { queueId: x.id, action: 'START_CONSULTATION', peerId: pid });
                                    onStartCall(x.callRoomId, x.name, null);
                                });
                            }}>CONSULT &gt;</button>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

// --- Root Component & Auth ---

const App = () => {
    const { user, token, logout } = useContext(AuthContext);
    const [view, setView] = useState('DASHBOARD');
    const [activeCall, setActiveCall] = useState(null);

    if (!token) return <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><LoginPortal /></div>;

    return (
        <div style={{ minHeight: '100vh', background: 'var(--background)' }}>
            <nav className="glass-nav" style={{ padding: '1rem 3rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, zIndex: 1000 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', cursor: 'pointer' }} onClick={() => setView('DASHBOARD')}><Activity color="var(--primary)" size={32} /><h2>SAHAY</h2></div>
                <div style={{ display: 'flex', gap: '2rem', alignItems: 'center' }}>
                    <div style={{ fontWeight: '900', color: 'var(--primary)', background: 'var(--primary-light)', padding: '0.5rem 1.5rem', borderRadius: '12px' }}>{user.name}</div>
                    <button onClick={logout} style={{ color: '#ef4444' }}><LogOut size={22} /></button>
                </div>
            </nav>
            <main className="container">
                {user.role === 'PATIENT' ? (
                    <>
                        {view === 'DASHBOARD' && <PatientDashboard user={user} setView={setView} onStartCall={(rid, dpid) => setActiveCall({ rid, name: "Consultation", dpid })} />}
                        {view === 'INTAKE' && <ConversationalIntake user={user} onComplete={() => setView('DASHBOARD')} />}
                    </>
                ) : <DoctorDashboard user={user} onStartCall={(rid, name, dpid) => setActiveCall({ rid, name, dpid })} />}
            </main>
            {activeCall && <div className="loading-overlay" style={{ background: '#09090b' }}><h1 style={{ color: 'white' }}>Live WebRTC Triage Session...</h1><button className="primary" style={{ marginTop: '3rem', background: '#ef4444', padding: '1rem 4rem' }} onClick={() => setActiveCall(null)}>DISCONNECT SESSION</button></div>}
        </div>
    );
};

const LoginPortal = () => {
    const { login } = useContext(AuthContext);
    const [p, setP] = useState(''); const [n, setN] = useState(''); const [r, setR] = useState('PATIENT');
    return (
        <div className="card" style={{ width: '380px', textAlign: 'center', padding: '4rem 3rem' }}>
            <Activity color="var(--primary)" size={48} /><h1 className="text-gradient" style={{ fontSize: '2.5rem' }}>SAHAY</h1>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', marginTop: '2.5rem' }}>
                <div className="input-group"><User size={20} /><input placeholder="Full Name" value={n} onChange={e => setN(e.target.value)} /></div>
                <div className="input-group"><PhoneCall size={20} /><input placeholder="Phone" value={p} onChange={e => setP(e.target.value)} /></div>
                <div style={{ display: 'flex', gap: '0.5rem', background: '#f1f5f9', padding: '0.4rem', borderRadius: '12px' }}>
                    <button className={r === 'PATIENT' ? 'primary' : 'outline'} style={{ flex: 1, border: 'none' }} onClick={() => setR('PATIENT')}>Patient</button>
                    <button className={r === 'DOCTOR' ? 'primary' : 'outline'} style={{ flex: 1, border: 'none' }} onClick={() => setR('DOCTOR')}>Doctor</button>
                </div>
                <button className="primary" style={{ padding: '1.2rem', fontSize: '1.1rem' }} onClick={() => login(p, n, r)}>LAUNCH CONSOLE</button>
            </div>
        </div>
    );
};

const ConversationalIntake = ({ user, onComplete }) => {
    const [chat, setChat] = useState([{ b: true, t: `Greetings ${user.name}. To generate your Clinical Report, please describe your current health condition.` }]);
    const [inp, setInp] = useState('');
    const [ans, setAns] = useState({});
    const [q, setQ] = useState({ id: 'mainSymptom', label: 'Describe symptoms...' });
    const [sym, setSym] = useState('');

    const send = async () => {
        if (!inp) return;
        const v = inp; setInp(''); setChat(p => [...p, { b: false, t: v }]);
        const nA = { ...ans, [q.id]: v }; setAns(nA);
        let nS = sym; if (q.id === 'mainSymptom') { nS = v; setSym(v); }
        const res = await axios.post(`${API_BASE}/intake/next-question`, { answers: nA, symptom: nS });
        if (res.data.isComplete) {
            setChat(p => [...p, { b: true, t: "Report processing... Synthesizing medical history with current condition." }]);
            await axios.post(`${API_BASE}/intake/finalize`, { userId: user.id, answers: nA, symptom: nS });
            setTimeout(() => onComplete(), 2000);
        } else {
            setQ(res.data.nextQuestion); setChat(p => [...p, { b: true, t: res.data.nextQuestion.label }]);
        }
    };
    return (
        <div className="container animate-up" style={{ maxWidth: '700px' }}>
            <div className="card" style={{ height: '550px', display: 'flex', flexDirection: 'column' }}>
                <div style={{ flex: 1, overflowY: 'auto', padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    {chat.map((m, i) => <div key={i} className={`chat-bubble ${m.b ? 'chat-bot' : 'chat-user'}`} style={{ padding: '1.2rem', borderRadius: '18px', fontSize: '1rem' }}>{m.t}</div>)}
                </div>
                <div className="input-group" style={{ margin: '1.5rem', background: '#f8fafc', border: '1px solid #eef2ff' }}><input placeholder="Reply to SAHAY AI..." value={inp} onChange={e => setInp(e.target.value)} onKeyPress={e => e.key === 'Enter' && send()} /><button className="primary" onClick={send}><Send size={20} /></button></div>
            </div>
        </div>
    );
};

const SetupProfile = ({ userId, onComplete }) => {
    const [step, setStep] = useState(1);
    const [form, setForm] = useState({ name: '', age: '', gender: 'Male', contact: '', address: '', height: '', weight: '', bloodGroup: 'B+', history: '' });
    const sub = async () => { await axios.post(`${API_BASE}/patient/update-profile`, { userId, ...form }); onComplete(); };
    return (
        <div className="container animate-up" style={{ maxWidth: '800px' }}>
            <h1 style={{ textAlign: 'center', marginBottom: '3rem' }}>Complete Patient Health Profile</h1>
            <div className="card">
                <div style={{ display: 'flex', justifyContent: 'center', gap: '2rem', marginBottom: '2rem' }}>
                    <span style={{ color: step === 1 ? 'var(--primary)' : '#94a3b8', fontWeight: '800' }}>1. PERSONAL</span>
                    <span style={{ color: step === 2 ? 'var(--primary)' : '#94a3b8', fontWeight: '800' }}>2. VITALS</span>
                    <span style={{ color: step === 3 ? 'var(--primary)' : '#94a3b8', fontWeight: '800' }}>3. HISTORY</span>
                </div>
                {step === 1 && <div style={{ display: 'grid', gap: '1.5rem' }}><div className="input-group"><User size={18} /><input placeholder="Full Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="input-group"><Clock size={18} /><input placeholder="Age" value={form.age} onChange={e => setForm({ ...form, age: e.target.value })} /></div><select style={{ width: '100%', padding: '1rem', borderRadius: '12px', border: 'none', background: 'var(--primary-light)' }} value={form.gender} onChange={e => setForm({ ...form, gender: e.target.value })}><option>Male</option><option>Female</option></select></div>}
                {step === 2 && <div style={{ display: 'grid', gap: '1.5rem' }}><div className="input-group"><Ruler size={18} /><input placeholder="Height (cm)" value={form.height} onChange={e => setForm({ ...form, height: e.target.value })} /></div><div className="input-group"><Scale size={18} /><input placeholder="Weight (kg)" value={form.weight} onChange={e => setForm({ ...form, weight: e.target.value })} /></div></div>}
                {step === 3 && <div style={{ display: 'grid', gap: '1.5rem' }}><textarea placeholder="Past Surgeries, Smoking Habits, Chronic Illnesses..." style={{ width: '100%', minHeight: '100px', border: 'none', background: 'var(--primary-light)', padding: '1rem', borderRadius: '16px' }} value={form.history} onChange={e => setForm({ ...form, history: e.target.value })} /></div>}
                <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '2.5rem' }}>
                    <button className="outline" onClick={() => setStep(step - 1)} style={{ opacity: step === 1 ? 0 : 1 }}>BACK</button>
                    <button className="primary" onClick={() => step === 3 ? sub() : setStep(step + 1)}>{step === 3 ? 'COMPLETE PROFILE' : 'NEXT STEP'}</button>
                </div>
            </div>
        </div>
    );
};

const useQueueSync = (userId) => {
    const [data, setData] = useState(null);
    useEffect(() => {
        const fetch = () => axios.get(`${API_BASE}/patient/status/${userId}`).then(res => setData(res.data));
        fetch(); socket.on('queue_updated', fetch); return () => socket.off('queue_updated', fetch);
    }, [userId]);
    return { data };
};

export default () => <AuthProvider><App /></AuthProvider>;
